"""Compares the figures and captions that scripts/15_figures_v2.py has just written with the committed ones (HEAD).

Planning session, 2 Oct 2026 (record, "The revision of 1–2 October 2026: the cold reads applied", its paragraph "The
figures"). Run from the repository root after `.venv/bin/python scripts/15_figures_v2.py`, at the text commit of the
revision (HEAD), before anything is committed:
    .venv/bin/python notes/review_2026-10-01_cold_reads/checks/figures_check.py
It tests the conditions of that paragraph and prints, for each, what it found:
 1. `manuscript/figures/captions_v2.md` has as many lines as HEAD's and differs from it in six lines only: its header
    line, which must name HEAD's short SHA (`git rev-parse --short HEAD`, without `-dirty`), and the captions of
    Figs 1, 3, 4, 5 and 6, each of which must hold a Source sentence and, without it, equal the main text's caption of
    that figure. Fig 2's caption must be HEAD's and, without its Source sentence, the main text's.
 2. The PNG files of Figs 1, 3 and 5 (redrawn: Fig 1b's colour-bar label; Fig 3c's two per-subject slope lines and
    its legend; Fig 5c's y-range, height and title) differ from HEAD's, each with a width and a height within 3 % of
    HEAD's. The PNG files of Figs 2, 4 and 6 are identical to HEAD's or differ by anti-aliasing alone, defined here
    as: the same size, at most 0.1 % of the pixels different, and no channel different by more than 32 of 255.
 3. The PDF files of Figs 1, 3 and 5 differ from HEAD's beyond their dates. Those of Figs 2, 4 and 6 are identical to
    HEAD's once the dates are masked: the two date fields (/CreationDate and /ModDate) and, because the byte offsets
    would move with a date of another length, the cross-reference table and the `startxref` offset.
It ends with "conditions met" (exit status 0) or names the conditions that are not met (exit status 1); it changes no
file.
"""
import io
import re
import subprocess
import sys
from pathlib import Path

import numpy as np
from PIL import Image

FIG = Path("manuscript/figures")
NAMES = ("fig1_v2_scope_map", "fig2_v2_atoms_observed_substituted", "fig3_v2_per_subject", "fig4_v2_regional",
         "fig5_v2_residual_diagnostic", "fig6_v2_lag_dependence")   # the six figures the script writes
REDRAWN = {1, 3, 5}                 # figures whose drawing changes at this commit
CAPTIONS_CHANGED = {1, 3, 4, 5, 6}  # captions that change at this commit (Fig 2's does not)
SIZE_TOL = 0.03                     # a redrawn figure's width and height against HEAD's
AA_SHARE, AA_MAX = 0.001, 32        # anti-aliasing alone: at most this share of pixels, by at most this much of 255
HEADER = "Generated by `scripts/15_figures_v2.py` at git "
failed = []


def fail(what):
    failed.append(what)
    return "NOT MET"


def git(*args):
    r = subprocess.run(["git", *args], capture_output=True)
    if r.returncode:
        sys.exit(f"git {' '.join(args)} failed: {r.stderr.decode(errors='replace').strip()}")
    return r.stdout


def committed(path):
    return git("show", f"HEAD:{path}")


def body(caption):
    """The caption without its Source sentence, or None if it has none."""
    i = caption.rfind(" Source: ")
    return caption[:i] if i > 0 else None


# ---------------------------------------------------------------- 1. the captions file
sha = git("rev-parse", "--short", "HEAD").decode().strip()
old = committed(f"{FIG}/captions_v2.md").decode("utf-8").split("\n")
new = (FIG / "captions_v2.md").read_text(encoding="utf-8").split("\n")
main = {int(m.group(1)): m.group(0) for m in
        re.finditer(r"^\*\*Fig (\d)\. .*$", Path("manuscript/draft_v2.md").read_text(encoding="utf-8"), re.M)}
print(f"1. captions_v2.md (HEAD is {sha})")
if len(old) != len(new):
    print(f"   {len(old)} lines at HEAD, {len(new)} now: {fail('captions: the number of lines')}")
seen = set()
for i in range(min(len(old), len(new))):
    m = re.match(r"\*\*Fig (\d)\. ", new[i])
    if new[i].startswith(HEADER) or old[i].startswith(HEADER):
        want = f"{HEADER}{sha}, seed "
        okh = new[i].startswith(want) and old[i].startswith(HEADER) and old[i] != new[i]
        print(f"   line {i + 1}, the header: {new[i][:len(want) + 8]!r}: "
              + ("names HEAD" if okh else fail(f"captions: the header does not begin {want!r} or is unchanged")))
        seen.add("header")
    elif m and old[i].startswith(f"**Fig {m.group(1)}. "):
        k = int(m.group(1)); seen.add(k)
        b = body(new[i])
        if k in CAPTIONS_CHANGED:
            okc = old[i] != new[i] and b is not None and b == main.get(k)
            why = ("changed, with a Source sentence, and equal to the main text's without it" if okc else
                   fail(f"captions: Fig {k}'s caption is unchanged, has no Source sentence or is not the main text's"))
        else:
            okc = old[i] == new[i] and b is not None and b == main.get(k)
            why = ("HEAD's, and the main text's without its Source sentence" if okc else
                   fail(f"captions: Fig {k}'s caption changed or is not the main text's"))
        print(f"   line {i + 1}, Fig {k}'s caption: {why}")
    elif old[i] != new[i]:
        print(f"   line {i + 1} differs and is neither the header nor a caption: {fail(f'captions: line {i + 1}')}\n"
              f"     HEAD: {old[i][:150]}\n     now:  {new[i][:150]}")
for k in ["header", 1, 2, 3, 4, 5, 6]:
    if k not in seen:
        print(f"   {k if k == 'header' else f'Fig {k}'}: not found: " + fail(f"captions: {k} not found"))

# ---------------------------------------------------------------- 2. the PNG files
print("2. the PNG files")
for k, png in enumerate((FIG / f"{n}.png" for n in NAMES), 1):
    a, b = committed(str(png)), png.read_bytes()
    if a == b:
        print(f"   {png.name}: identical to HEAD's" + (": " + fail(f"PNG: Fig {k} is not redrawn") if k in REDRAWN else ""))
        continue
    x = np.asarray(Image.open(io.BytesIO(a)).convert("RGBA"), dtype=int)
    y = np.asarray(Image.open(io.BytesIO(b)).convert("RGBA"), dtype=int)
    (h0, w0), (h1, w1) = x.shape[:2], y.shape[:2]
    if k in REDRAWN:
        oks = abs(w1 / w0 - 1) <= SIZE_TOL and abs(h1 / h0 - 1) <= SIZE_TOL
        print(f"   {png.name}: redrawn; {w0} × {h0} px at HEAD, {w1} × {h1} now ({100 * (w1 / w0 - 1):+.2f} % and "
              f"{100 * (h1 / h0 - 1):+.2f} %): " + ("within 3 %" if oks else fail(f"PNG: Fig {k}'s size")))
    elif x.shape != y.shape:
        print(f"   {png.name}: {w0} × {h0} px at HEAD, {w1} × {h1} now: " + fail(f"PNG: Fig {k}'s size changed"))
    else:
        d = np.abs(x - y)
        n = int(np.any(d > 0, axis=2).sum()); mx = int(d.max()); share = n / (h0 * w0)
        aa = share <= AA_SHARE and mx <= AA_MAX
        print(f"   {png.name}: differs in {n} pixels ({100 * share:.3f} %), the largest channel difference {mx} of 255: "
              + ("anti-aliasing alone" if aa else fail(f"PNG: Fig {k} differs beyond anti-aliasing")))

# ---------------------------------------------------------------- 3. the PDF files
DATES = re.compile(rb"/(CreationDate|ModDate) \(D:[^)]*\)")


def masked(p):
    """The PDF with its two date fields masked, and its cross-reference table and `startxref` offset with them."""
    p = DATES.sub(b"/DATE", p)
    p = re.sub(rb"\nxref\n.*?\ntrailer", b"\nxref trailer", p, flags=re.S)
    return re.sub(rb"startxref\n\d+", b"startxref", p)


print("3. the PDF files")
for k, pdf in enumerate((FIG / f"{n}.pdf" for n in NAMES), 1):
    a, b = committed(str(pdf)), pdf.read_bytes()
    same = a == b or masked(a) == masked(b)
    if k in REDRAWN:
        print(f"   {pdf.name}: " + ("differs beyond its dates (redrawn)" if not same else
                                    "identical but for its dates: " + fail(f"PDF: Fig {k} is not redrawn")))
    else:
        print(f"   {pdf.name}: " + (("identical" if a == b else "identical once its dates are masked") if same else
                                    "differs beyond its dates: " + fail(f"PDF: Fig {k} changed")))

if failed:
    print("conditions NOT met (" + "; ".join(failed) + "): send this output to the planning session")
    sys.exit(1)
print("conditions met")
