# The 22 September 2026 review's check script, as run in the planning session's sandbox against 0b8d1a4; paths made repository-relative in round 16.
# Its printed values are quoted in the review and are not regenerated by run_all.sh.
import pickle, numpy as np, itertools
from scipy import stats
from pathlib import Path; B=str(Path(__file__).resolve().parents[2] / 'review_results') + '/'
def get(f, label, s='primary'):
    d=pickle.load(open(B+f,'rb'))
    for r in d:
        if r['label']==label and r['set']==s: return np.asarray(r['did_subjects'],float), r
    raise KeyError(label)
signs=np.array(list(itertools.product([1,-1],repeat=14)))
def signflip(x, mu0=0.0):
    y=x-mu0; obs=abs(y.mean()); null=np.abs((signs*y).mean(1)); return (null>=obs-1e-15).mean()
def tci(x):
    m=x.mean(); se=x.std(ddof=1)/np.sqrt(len(x)); t=stats.t.ppf(0.975,len(x)-1); return m-t*se,m+t*se, se
