# The 22 September 2026 review's check script, as run in the planning session's sandbox against 0b8d1a4; paths made repository-relative in round 16.
# Its printed values are quoted in the review and are not regenerated by run_all.sh.
import sys; from pathlib import Path; sys.path.insert(0, str(Path(__file__).resolve().parents[2]))
import numpy as np
from rev_phiid_fast import atoms_from_corr, ar1_corr
S=15
rng=np.random.default_rng(11)
qpool=np.clip(rng.normal(0,0.3424,20000),-0.8,0.8)
for a in [0.85, 0.8632]:
    base=ar1_corr(a,a,qpool)
    s0=atoms_from_corr(base)[:,S]
    print(f'a={a}: pool mean sts (AR1) {s0.mean():.4f}')
    for dl in [0.005, 0.01, 0.02]:
        for kind in ['uniform +','uniform -','aligned +','aligned -']:
            sgn = 1 if kind.endswith('+') else -1
            d = sgn*dl*(np.sign(qpool) if kind.startswith('aligned') else 1.0)
            C=base.copy(); C[:,0,3]+=d; C[:,3,0]+=d; C[:,1,2]+=d; C[:,2,1]+=d
            ok=np.all(np.linalg.eigvalsh(C)>0,axis=1)
            s=atoms_from_corr(C[ok])[:,S]
            print(f'   delta {kind}{dl}: population residual (pool mean sts - AR1 prediction) {np.mean(s-s0[ok]):+.5f}  (valid {ok.mean():.3f})')
