# The 22 September 2026 review's check script, as run in the planning session's sandbox against 0b8d1a4; paths made repository-relative in round 16.
# Its printed values are quoted in the review and are not regenerated by run_all.sh.
from var1 import *
import numpy as np
S=15
def sts_pop_matched(c, q, r1=0.85):
    # coupled symmetric VAR(1) with (a, rho) re-solved so that r1 and q are held; returns sts(true) - sts(AR1 substitution)
    a, rho, M = solve_sym(c, r1, q)
    obs = atoms(M)['sts']
    pred = atoms(ar1_corr(M[0,2], M[1,3], 0.5*(M[0,1]+M[2,3])))[0][S] if False else atoms_from_corr(ar1_corr(M[0,2], M[1,3], 0.5*(M[0,1]+M[2,3])))[0][S]
    return obs - pred
qs = np.linspace(0.05, 0.6, 12)
print('matched (r1,q held) population residual, by |q|, c = +0.02 at q>0 vs q<0:')
for q in [0.1, 0.25, 0.4]:
    print(f'  q={q}: c=+0.02 aligned {sts_pop_matched(0.02,q):+.5f} ; c=+0.02 at q=-{q} (anti-aligned) {sts_pop_matched(0.02,-q):+.5f}; c=-0.02 at +q {sts_pop_matched(-0.02,q):+.5f}')
# pool average with q ~ N(0, 0.3424) clipped
rng=np.random.default_rng(0)
qpool = np.clip(rng.normal(0,0.3424,400), -0.8, 0.8)
for c in [0.01, 0.02, -0.02, 0.03]:
    uni = np.mean([sts_pop_matched(c, q) for q in qpool])
    ali = np.mean([sts_pop_matched(c*np.sign(q), q) for q in qpool])
    print(f'c={c:+.2f}: uniform-sign pool-mean residual {uni:+.5f}; aligned (c*sign q) pool-mean residual {ali:+.5f}')
