# The 22 September 2026 review's check script, as run in the planning session's sandbox against 0b8d1a4; paths made repository-relative in round 16.
# Its printed values are quoted in the review and are not regenerated by run_all.sh.
import sys; from pathlib import Path; sys.path.insert(0, str(Path(__file__).resolve().parents[2]))
import numpy as np
from scipy.linalg import solve_discrete_lyapunov
from scipy.optimize import fsolve
from rev_phiid_fast import atoms_from_corr, ar1_corr, ATOMS

def var1_corr4(A, Sig):
    G0 = solve_discrete_lyapunov(A, Sig)
    G1 = A @ G0            # E[z_{t+1} z_t^T]
    M = np.block([[G0, G1.T],[G1, G0]])
    d = np.sqrt(np.diag(M))
    return M/np.outer(d,d)

def sym_var1(a, c, rho):
    A = np.array([[a,c],[c,a]]); S = np.array([[1,rho],[rho,1]])
    return var1_corr4(A,S)

def solve_sym(c, r1=0.85, q=0.25):
    def f(p):
        a, rho = p
        M = sym_var1(a,c,rho)
        return [M[0,2]-r1, M[0,1]-q]
    a, rho = fsolve(f, [r1, q])
    return a, rho, sym_var1(a,c,rho)

def atoms(M):
    return dict(zip(ATOMS, atoms_from_corr(M)[0]))
