# The 22 September 2026 review's check script, as run in the planning session's sandbox against 0b8d1a4; paths made repository-relative in round 16.
# Its printed values are quoted in the review and are not regenerated by run_all.sh.
import sys
from var1 import *
import numpy as np
S = 15
rng = np.random.default_rng(20260922)
NP = 40000          # pair-windows per condition
W = 60; BURN = 200
qpool = np.clip(rng.normal(0, 0.3424, NP), -0.8, 0.8)
z1 = rng.standard_normal((NP, W + BURN + 1)); z2 = rng.standard_normal((NP, W + BURN + 1))
# precompute (a, rho) per unique rounded q for each c
def params(c_arr, q_arr):
    out_a = np.empty(NP); out_r = np.empty(NP)
    cache = {}
    for i,(c,q) in enumerate(zip(c_arr, q_arr)):
        key = (round(c,4), round(q,3))
        if key not in cache:
            a, rho, M = solve_sym(key[0], 0.85, key[1]); cache[key] = (a, rho)
        out_a[i], out_r[i] = cache[key]
    return out_a, out_r
def simulate(c_arr, q_arr):
    qr = np.round(q_arr, 3)
    a, rho = params(c_arr, qr)
    c = np.round(c_arr, 4)
    eps = z1; eta = rho[:, None] * z1 + np.sqrt(1 - rho[:, None] ** 2) * z2
    x = np.zeros(NP); y = np.zeros(NP)
    X = np.empty((NP, W + 1)); Y = np.empty((NP, W + 1))
    for t in range(W + BURN + 1):
        x, y = a * x + c * y + eps[:, t], a * y + c * x + eta[:, t]
        if t >= BURN:
            X[:, t - BURN] = x; Y[:, t - BURN] = y
    # phyid-style: past = [:-1], future = [1:], each standardised
    def st(v): v = v - v.mean(1, keepdims=True); return v / v.std(1, ddof=1, keepdims=True)
    P1, P2, F1, F2 = st(X[:, :-1]), st(Y[:, :-1]), st(X[:, 1:]), st(Y[:, 1:])
    Z = np.stack([P1, P2, F1, F2], 1)                     # (NP, 4, W)
    C = np.einsum('nit,njt->nij', Z, Z) / (W - 1)
    obs = atoms_from_corr(C)[:, S]
    ax, ay, qq = C[:, 0, 2], C[:, 1, 3], 0.5 * (C[:, 0, 1] + C[:, 2, 3])
    pred = atoms_from_corr(ar1_corr(ax, ay, qq))[:, S]
    return obs, pred
base_o, base_p = simulate(np.zeros(NP), qpool)
print('c=0: obs %.4f pred %.4f resid %.4f' % (base_o.mean(), base_p.mean(), (base_o - base_p).mean()))
for label, carr in [('uniform +0.02', np.full(NP, 0.02)), ('uniform -0.02', np.full(NP, -0.02)),
                    ('aligned +0.02', 0.02 * np.sign(qpool)), ('aligned -0.02', -0.02 * np.sign(qpool)),
                    ('aligned +0.01', 0.01 * np.sign(qpool)), ('aligned -0.01', -0.01 * np.sign(qpool))]:
    o, p = simulate(carr, qpool)
    d = (o - p) - (base_o - base_p)
    print(f'{label}: Δobs {np.mean(o-base_o):+.4f}  Δpred {np.mean(p-base_p):+.4f}  Δresidual {d.mean():+.4f} ± {d.std()/np.sqrt(NP):.4f} (SE)')
