# The 22 September 2026 review's check script, as run in the planning session's sandbox against 0b8d1a4; paths made repository-relative in round 16.
# Its printed values are quoted in the review and are not regenerated by run_all.sh.
from var1 import *
import numpy as np
S = 15
rng = np.random.default_rng(7)
NP = 40000; W = 60; BURN = 200
qpool = np.clip(rng.normal(0, 0.3424, NP), -0.8, 0.8)
z1 = rng.standard_normal((NP, W + BURN + 1)); z2 = rng.standard_normal((NP, W + BURN + 1))
a = 0.85
def simulate(c, rho):
    eps = z1; eta = rho[:, None] * z1 + np.sqrt(1 - rho[:, None] ** 2) * z2
    x = np.zeros(NP); y = np.zeros(NP); X = np.empty((NP, W + 1)); Y = np.empty((NP, W + 1))
    for t in range(W + BURN + 1):
        x, y = a * x + c * y + eps[:, t], a * y + c * x + eta[:, t]
        if t >= BURN: X[:, t - BURN] = x; Y[:, t - BURN] = y
    def st(v): v = v - v.mean(1, keepdims=True); return v / v.std(1, ddof=1, keepdims=True)
    Z = np.stack([st(X[:, :-1]), st(Y[:, :-1]), st(X[:, 1:]), st(Y[:, 1:])], 1)
    C = np.einsum('nit,njt->nij', Z, Z) / (W - 1)
    obs = atoms_from_corr(C)[:, S]
    pred = atoms_from_corr(ar1_corr(C[:, 0, 2], C[:, 1, 3], 0.5 * (C[:, 0, 1] + C[:, 2, 3])))[:, S]
    return obs, pred, C
rho = qpool.copy()   # at c = 0 with equal a, the lag-0 correlation equals the innovation correlation
o0, p0, C0 = simulate(0.0, rho)
print('calibration-style (innovations fixed): c=0 obs %.4f pred %.4f res %.4f mean|q| %.4f' % (o0.mean(), p0.mean(), (o0-p0).mean(), np.abs(0.5*(C0[:,0,1]+C0[:,2,3])).mean()))
for c in [0.01, 0.02, 0.03, -0.02]:
    o, p, C = simulate(c, rho)
    d = (o - p) - (o0 - p0)
    print(f'  c={c:+.2f}: dobs {np.mean(o-o0):+.4f} dpred {np.mean(p-p0):+.4f} dresid {d.mean():+.4f} ± {d.std()/np.sqrt(NP):.4f}; mean q shift {np.mean(0.5*(C[:,0,1]+C[:,2,3]) - 0.5*(C0[:,0,1]+C0[:,2,3])):+.3f}')
