#!/usr/bin/env python3
"""
12_figures.py — manuscript figures, all regenerable from saved results.

Reads only files already in results/ and the source data; never recomputes an
estimator. Where a per-subject quantity is not stored in a table (the
per-subject DiD behind Figure 2), it is derived from the saved window-mean
atoms with the identical definition used by 06_primary_b_analysis.py and the
group mean is asserted equal to the table's value before anything is drawn.

Outputs (manuscript/figures/):
  fig1_sts_timecourse_ts_gsr_win60.{png,pdf}
  fig2_per_subject_did.{png,pdf}
  fig3_regional_did_ts_gsr.{png,pdf}
  captions.md                       captions with provenance line
Prints, for every figure, the numbers it drew so they can be checked against
results/*.csv and manuscript/analysis_record.md.

Inputs:
  results/atoms_win60_115regions-all_{ts_gsr,ts_demean}_window.npy  (14, 2, 14, 16)
  results/primary_b_{ts_gsr,ts_demean}_win60.csv                    group DiD, CI, p
  results/regional_did_map_ts_gsr.csv                               115 rows
  results/regional_analysis_ts_gsr.csv                              BH threshold, counts
  external/DMT_NCT/data/intensity_ratings.mat                       dmt_intensity (14, 28)

Usage: python3 scripts/12_figures.py
"""
import csv
import subprocess
from pathlib import Path

import matplotlib
matplotlib.use("Agg")                       # file output only; no interactive backend assumed
import matplotlib.pyplot as plt
from matplotlib.patches import Patch
from matplotlib.lines import Line2D
import numpy as np
import scipy.io as sio

SEED = 20261120
rng = np.random.default_rng(SEED)           # no stochastic step in this script; kept so any future jitter is seeded

N_SUBJ, N_TRS, N_BINS = 14, 840, 28
W = 60
N_WIN = N_TRS // W                          # 14
STS = 15                                    # phyid atom order: rtr,rtx,rty,rts,xtr,xtx,xty,xts,ytr,ytx,yty,yts,str,stx,sty,sts
TR_SEC = 2.0
PRE = np.arange(0, 4)                       # windows 1-4   (bins 1-8)
POST_PRIMARY = np.arange(5, 14)             # windows 6-14  (bins 11-28)
EXCLUDED_WIN = 4                            # window 5 (bins 9-10), 0-based
INJECTION_MIN = 8.0                         # TR 240 = end of minute 8
NETS = {1: "Vis", 2: "SomMot", 3: "DorsAttn", 4: "SalVentAttn", 5: "Limbic", 6: "Cont", 7: "Default", 8: "Subcortex"}
NET_COLOURS = {1: "#781286", 2: "#4682B4", 3: "#00760E", 4: "#C43AFA", 5: "#DCF8A4", 6: "#E69422", 7: "#CD3E4E", 8: "#7F7F7F"}

RESULTS = Path("results")
DATA = Path("external/DMT_NCT/data")
FIGS = Path("manuscript/figures")
FIGS.mkdir(parents=True, exist_ok=True)

plt.rcParams.update({
    "font.size": 9, "axes.titlesize": 10, "axes.labelsize": 9, "legend.fontsize": 8,
    "xtick.labelsize": 8, "ytick.labelsize": 8, "axes.spines.top": False, "axes.spines.right": False,
    "savefig.dpi": 300, "pdf.fonttype": 42,
})

try:
    sha = subprocess.check_output(["git", "rev-parse", "--short", "HEAD"], text=True).strip()
    if subprocess.check_output(["git", "status", "--porcelain", "--", "scripts", "manuscript/analysis_record.md"], text=True).strip():
        sha += "-dirty"
except Exception:
    sha = "nogit"
print(f"12_figures.py  seed={SEED}  git={sha}")


# ---------------------------------------------------------------- helpers
def read_csv_rows(path):
    with open(path) as f:
        lines = [ln for ln in f if not ln.startswith("#")]
    return list(csv.DictReader(lines))


def primary_b_row(variant, statistic):
    rows = read_csv_rows(RESULTS / f"primary_b_{variant}_win60.csv")
    hit = [r for r in rows if r["section"] == "A.primary" and r["statistic"] == statistic]
    assert len(hit) == 1, (variant, statistic, len(hit))
    r = hit[0]
    return float(r["value"]), float(r["ci_lo"]), float(r["ci_hi"]), float(r["p"]), r["note"]


def primary_b_value(variant, section, statistic):
    rows = read_csv_rows(RESULTS / f"primary_b_{variant}_win60.csv")
    hit = [r for r in rows if r["section"] == section and r["statistic"] == statistic]
    assert len(hit) == 1, (variant, section, statistic, len(hit))
    return float(hit[0]["value"])


def save(fig, stem):
    for ext in ("png", "pdf"):
        fig.savefig(FIGS / f"{stem}.{ext}", bbox_inches="tight")
    plt.close(fig)
    print(f"  wrote {FIGS / stem}.png / .pdf")


def load_sts(variant):
    path = RESULTS / f"atoms_win{W}_115regions-all_{variant}_window.npy"
    atoms = np.load(path)
    assert atoms.shape == (N_SUBJ, 2, N_WIN, 16), atoms.shape
    sts = atoms[..., STS]                                       # (14, 2, 14); index 0 = DMT, 1 = PCB
    assert np.isfinite(sts).all()
    return sts, path.name


captions = [f"# Figure captions\n\nGenerated by `scripts/12_figures.py` at git {sha}, seed {SEED}. "
            "Every value is read from the saved results files named under each figure.\n"]

# ================================================================ Figure 1
print("\n== Figure 1: whole-brain mean sts per window, ts_gsr, W=60")
sts, sts_file = load_sts("ts_gsr")
gm = sts.mean(0)                                                # (2, 14) group mean
sem = sts.std(0, ddof=1) / np.sqrt(N_SUBJ)                      # (2, 14) SEM across 14 subjects
t_win = (np.arange(N_WIN) + 0.5) * W * TR_SEC / 60.0            # window centres, minutes

# check against the table before drawing
pre_dmt_csv = primary_b_value("ts_gsr", "A", "pre-injection DMT mean sts (windows 1-4)")
pre_pcb_csv = primary_b_value("ts_gsr", "A", "pre-injection PCB mean sts (windows 1-4)")
pre_dmt = sts[:, 0, PRE].mean()
pre_pcb = sts[:, 1, PRE].mean()
assert abs(pre_dmt - pre_dmt_csv) < 1e-9 and abs(pre_pcb - pre_pcb_csv) < 1e-9, (pre_dmt, pre_dmt_csv, pre_pcb, pre_pcb_csv)
print(f"  source: {sts_file}; pre-injection means DMT {pre_dmt:.4f} PCB {pre_pcb:.4f} (match primary_b_ts_gsr_win60.csv)")

ratings = sio.loadmat(DATA / "intensity_ratings.mat")
dmt_int = ratings["dmt_intensity"].astype(float)                # (14, 28)
pcb_int = ratings["pcb_intensity"].astype(float)
assert dmt_int.shape == (N_SUBJ, N_BINS)
int_mean = dmt_int.mean(0)                                      # group-mean DMT intensity per rating bin
pcb_int_mean = pcb_int.mean(0)
t_bin = (np.arange(N_BINS) + 0.5) * 30 * TR_SEC / 60.0          # bin centres, minutes

print("  window  t(min)  DMT mean  DMT SEM  PCB mean  PCB SEM")
for w in range(N_WIN):
    print(f"  {w + 1:6d}  {t_win[w]:6.1f}  {gm[0, w]:8.4f}  {sem[0, w]:7.4f}  {gm[1, w]:8.4f}  {sem[1, w]:7.4f}")
print("  group-mean DMT intensity per bin: " + " ".join(f"{v:.2f}" for v in int_mean))
print("  group-mean PCB intensity per bin: " + " ".join(f"{v:.2f}" for v in pcb_int_mean))

fig, ax = plt.subplots(figsize=(6.5, 3.9))
ax.axvspan(0, INJECTION_MIN, color="0.92", zorder=0, label="pre-injection windows 1–4")
ax.axvspan(INJECTION_MIN, INJECTION_MIN + W * TR_SEC / 60.0, facecolor="none", edgecolor="0.5", hatch="///",
           linewidth=0, zorder=0, label="window 5, excluded from primary post set")
ax.axvline(INJECTION_MIN, color="k", linewidth=0.8, linestyle="--", zorder=1)
ax.text(INJECTION_MIN, 1.0, " injection", transform=ax.get_xaxis_transform(), va="top", ha="left", fontsize=8)
for c, (lab, col) in enumerate((("DMT", "#C0392B"), ("placebo", "#2C6FAF"))):
    ax.fill_between(t_win, gm[c] - sem[c], gm[c] + sem[c], color=col, alpha=0.2, linewidth=0)
    ax.plot(t_win, gm[c], color=col, marker="o", markersize=3, linewidth=1.4, label=f"sts, {lab}")
ax.set_xlabel("time in scan (min)")
ax.set_ylabel("whole-brain mean sts (nats)")
ax.set_xlim(0, N_TRS * TR_SEC / 60.0)
ax2 = ax.twinx()
ax2.plot(t_bin, int_mean, color="0.25", linewidth=1.0, linestyle=":", label="intensity, DMT (group mean)")
ax2.set_ylabel("subjective intensity (0–10)")
ax2.set_ylim(-0.3, 10.5)
ax2.spines["right"].set_visible(True)
h1, l1 = ax.get_legend_handles_labels()
h2, l2 = ax2.get_legend_handles_labels()
ax.legend(h1 + h2, l1 + l2, loc="upper center", bbox_to_anchor=(0.5, -0.2), ncol=3, frameon=False)  # below the axes: nothing drawn is covered
fig.tight_layout()
save(fig, "fig1_sts_timecourse_ts_gsr_win60")
captions.append(
    "\n## Figure 1\n\n"
    "Whole-brain mean synergy (sts atom, mean over 6,555 region pairs) per 60-TR window under DMT and placebo, "
    f"ts_gsr variant, windowed estimator (model refit per window), W = 60 TRs (2 min), N = {N_SUBJ}. Lines are the "
    "group mean across the 14 subjects, shading is ± 1 SEM. The dashed line marks intravenous injection at 8 min "
    "(TR 240). The grey band is the pre-injection window set (windows 1–4); the hatched band is window 5 (bins 9–10), "
    "excluded from the primary post-injection set on the onset-contamination evidence and included only in the "
    "sensitivity set. The dotted line (right axis) is the group-mean DMT intensity rating per 60-s bin; individual "
    "ratings are not shown. Source: `results/atoms_win60_115regions-all_ts_gsr_window.npy`, "
    "`external/DMT_NCT/data/intensity_ratings.mat`.\n")

# ================================================================ Figure 2
print("\n== Figure 2: per-subject DiD, primary windows 6-14 vs 1-4, W=60")
fig, axes = plt.subplots(1, 2, figsize=(6.5, 3.4), sharey=False)
for ax, variant in zip(axes, ("ts_gsr", "ts_demean")):
    sts_v, sts_file = load_sts(variant)
    change = sts_v[:, :, POST_PRIMARY].mean(2) - sts_v[:, :, PRE].mean(2)   # identical to did() in 06
    did = change[:, 0] - change[:, 1]                                          # (14,)
    mean_csv, lo, hi, p, note = primary_b_row(variant, "DiD raw: mean")
    assert abs(did.mean() - mean_csv) < 1e-9, (variant, did.mean(), mean_csv)
    n_neg = int((did < 0).sum())
    print(f"  {variant}: source {sts_file}; per-subject DiD (subject order 1-14): "
          + " ".join(f"{v:+.4f}" for v in did))
    print(f"  {variant}: mean {mean_csv:+.4f} [{lo:+.4f}, {hi:+.4f}] p={p:.4f}  negative {n_neg}/14  ({note})")
    order = np.argsort(did)
    x = np.arange(N_SUBJ)
    ax.axhline(0, color="k", linewidth=0.8, zorder=1)
    ax.axhspan(lo, hi, color="#C0392B", alpha=0.15, linewidth=0, zorder=0, label="bootstrap 95 % CI of mean")
    ax.axhline(mean_csv, color="#C0392B", linewidth=1.2, zorder=2, label="group mean")
    ax.scatter(x, did[order], s=22, color="0.2", zorder=3, label="subject")
    for xi, si in zip(x, order):
        ax.annotate(f"{si + 1}", (xi, did[si]), xytext=(0, 4.5), textcoords="offset points",
                    fontsize=6, ha="center", va="bottom", color="0.35")
    ax.set_xticks([])
    ax.set_xlabel("subjects, ordered by DiD")
    ax.set_title(f"{variant}\nDiD {mean_csv:+.4f} [{lo:+.4f}, {hi:+.4f}], p = {p:.4f}", fontsize=8.5)
    ax.set_ylabel("DiD in whole-brain mean sts (nats)")
axes[0].legend(loc="upper left", frameon=False)
fig.tight_layout()
save(fig, "fig2_per_subject_did")
captions.append(
    "\n## Figure 2\n\n"
    "Per-subject difference-in-differences (DiD) in whole-brain mean sts: (post − pre) on the DMT run minus "
    "(post − pre) on the placebo run, pre = windows 1–4 (bins 1–8), post = primary windows 6–14 (bins 11–28), "
    f"W = 60, N = {N_SUBJ}. Left: ts_gsr; right: ts_demean. One dot per subject (subject index labelled), ordered "
    "by value; the horizontal line is the group mean and the band its subject-bootstrap 95 % CI (10,000 draws, "
    "seed 20261120); zero is marked. The p value in each title is from the exact sign-flip permutation test across "
    "the 14 subjects (all 2^14 = 16,384 assignments, two-sided). The pre-specified direction was positive. Group "
    "mean, CI and p are read from `results/primary_b_<variant>_win60.csv`; the per-subject values are derived from "
    "`results/atoms_win60_115regions-all_<variant>_window.npy` with the same window sets, and their mean is "
    "asserted equal to the table value before drawing.\n")

# ================================================================ Figure 3
print("\n== Figure 3: regional DiD map, ts_gsr, EXPLORATORY")
rows = read_csv_rows(RESULTS / "regional_did_map_ts_gsr.csv")
assert len(rows) == 115, len(rows)
idx = np.array([int(r["orig_index"]) for r in rows])
name = np.array([r["name"] for r in rows])
net = np.array([int(r["yeo_network"]) for r in rows])
did_map = np.array([float(r["did_mean"]) for r in rows])
pval = np.array([float(r["p_signflip"]) for r in rows])
bh = np.array([int(r["bh_significant"]) for r in rows]).astype(bool)
n_neg_map = int((did_map < 0).sum())

summary = read_csv_rows(RESULTS / "regional_analysis_ts_gsr.csv")
def summary_value(section, name_):
    hit = [r for r in summary if r["section"] == section and r["name"] == name_]
    assert len(hit) == 1, (section, name_)
    return hit[0]
n_neg_csv = int(float(summary_value("regional_did", "n_groupmean_negative_of_115")["value"]))
n_fdr_csv = int(float(summary_value("regional_did", "n_regions_fdr_significant")["value"]))
bh_note = summary_value("regional_did", "n_regions_fdr_significant")["note"]      # e.g. "BH q=0.05, p_thresh=0.00304"
assert n_neg_map == n_neg_csv, (n_neg_map, n_neg_csv)
assert int(bh.sum()) == n_fdr_csv, (bh.sum(), n_fdr_csv)
mean_over_regions = did_map.mean()
print(f"  source: regional_did_map_ts_gsr.csv; negative {n_neg_map}/115 (table: {n_neg_csv}); "
      f"FDR survivors {int(bh.sum())} (table: {n_fdr_csv}; {bh_note}); mean over regions {mean_over_regions:+.6f}")
print("  FDR survivors: " + "; ".join(f"{name[i]} (idx {idx[i]}, net {net[i]}, DiD {did_map[i]:+.4f}, p {pval[i]:.5f})"
                                      for i in np.flatnonzero(bh)))
print(f"  positive region(s): " + "; ".join(f"{name[i]} (idx {idx[i]}, DiD {did_map[i]:+.4f}, p {pval[i]:.3f})"
                                             for i in np.flatnonzero(did_map > 0)))

# order: by network, then by DiD within network (most negative first); two panels so that
# the 115 rows are legible at page width (left: networks 1-4, 57 rows; right: networks 5-8, 58 rows)
order = np.lexsort((did_map, net))
panels = [order[net[order] <= 4], order[net[order] >= 5]]
assert sum(p_.size for p_ in panels) == 115
xlo = min(did_map.min(), 0.0) - 0.015
xhi = max(did_map.max(), 0.0) + 0.015
fig, axes = plt.subplots(1, 2, figsize=(7.0, 9.2))
for ax, ord_ in zip(axes, panels):
    y = np.arange(ord_.size)
    ax.barh(y, did_map[ord_], color=[NET_COLOURS[n] for n in net[ord_]], edgecolor="none", height=0.8)
    ax.axvline(0, color="k", linewidth=0.8)
    ax.axvline(mean_over_regions, color="k", linewidth=0.8, linestyle=":")
    for yi, i in enumerate(ord_):
        if bh[i]:
            ax.plot(did_map[i] - 0.006, yi, marker="*", color="k", markersize=6, zorder=3)
    ax.set_yticks(y)
    ax.set_yticklabels([f"{name[i]}{' *' if bh[i] else ''}" for i in ord_], fontsize=6.5)
    for tick, i in zip(ax.get_yticklabels(), ord_):
        if bh[i]:
            tick.set_fontweight("bold")
    ax.set_ylim(-0.7, ord_.size - 0.3)
    ax.invert_yaxis()
    ax.set_xlim(xlo, xhi)
    ax.set_xlabel("regional DiD in mean sts (nats)")
    for b in np.flatnonzero(np.diff(net[ord_])) + 0.5:          # network boundaries
        ax.axhline(b, color="0.7", linewidth=0.5)
fig.suptitle("Regional synergy change under DMT, ts_gsr, global fit — EXPLORATORY", fontsize=10, y=0.995)
handles = [Patch(color=NET_COLOURS[k], label=NETS[k]) for k in sorted(NETS)]
handles.append(Line2D([0], [0], marker="*", color="k", linestyle="none", markersize=7, label="survives BH FDR, q = 0.05"))
handles.append(Line2D([0], [0], color="k", linestyle=":", linewidth=0.8, label=f"mean over regions {mean_over_regions:+.4f}"))
fig.legend(handles=handles, loc="lower center", bbox_to_anchor=(0.5, -0.005), ncol=5, frameon=False, fontsize=7.5)
fig.tight_layout(rect=(0, 0.035, 1, 0.985))
save(fig, "fig3_regional_did_ts_gsr")
captions.append(
    "\n## Figure 3 (exploratory)\n\n"
    "Exploratory regional map of the DMT synergy change, ts_gsr, Robustness A global fit, in two panels sharing "
    "one x axis (left: visual, somatomotor, dorsal-attention and salience/ventral-attention networks; right: limbic, "
    "control, default and subcortex). For each of the 115 "
    "regions (Schaefer-100 cortical parcels plus 16 subcortical parcels; region 20 excluded), the bar is the "
    "14-subject group mean of the per-subject DiD in that region's mean sts over its 114 pairs: (post bins 11–28 "
    "− pre bins 1–8) on DMT minus the same on placebo. Bars are grouped by Yeo-7 network (plus subcortex) and "
    "ordered by value within network; colour = network. Stars and bold labels mark regions surviving "
    f"Benjamini–Hochberg FDR at q = 0.05 across the 115 regions ({bh_note}; exact sign-flip test per region, "
    f"two-sided): {int(bh.sum())} regions, all negative, all cortical. {n_neg_map} of 115 group-mean DiDs are "
    "negative. The dotted line in both panels is the mean over regions, which equals the whole-brain pair-mean DiD on "
    "the same bins. This analysis was specified after the primary result and is exploratory; no motion handling and no "
    "temporal null are applied at the regional level. Source: `results/regional_did_map_ts_gsr.csv`, "
    "`results/regional_analysis_ts_gsr.csv`.\n")

with open(FIGS / "captions.md", "w") as f:
    f.write("".join(captions))
print(f"\nwrote {FIGS / 'captions.md'}")
