"""
15_figures_v2.py — manuscript figures for draft_v2 (the methods frame), drawn from saved results only.

Figure 1  the sixteen Gaussian atoms under MMI and under CCS (published double-redundancy definition),
          DMT pre-injection level and primary DiD, ts_gsr, W = 60  (results/atoms_win60_*.npy,
          notes/review_results/partB/ccs_pub_atoms_win60_ts_gsr.npy)
Figure 2  the (r1, q) scope map of the bivariate AR(1) family: sts, sts − (xtx + yty), the derivative ratio
          |∂sts/∂r1| / |∂sts/∂q| (contours; the ratio = 1 boundary does not exist on the grid) with the real
          pairs overlaid  (closed form, notes/rev_phiid_fast.py; overlay notes/review_results/partB/scope_map_overlay_points.npz)
Figure 3  per subject: (a) MMI-sts DiD against the lag-1 autocorrelation DiD; (b) CCS-sts DiD (published
          definition) against the residual DiD of the diagnostic  (notes/review_results/inference_rows_{raw,ccs_pub,diag}.pkl)
Figure 4  the residual diagnostic by window: observed, AR(1)-predicted and residual whole-brain sts,
          DMT and placebo, group mean ± SEM  (notes/review_results/partB/diag_series_ts_gsr_W60.npz)
Outputs manuscript/figures/fig{1..4}_v2_*.{png,pdf} and manuscript/figures/captions_v2.md. The v1 figures are left in place.
Run from the repository root: .venv/bin/python scripts/15_figures_v2.py
"""
import pickle
import subprocess
import sys
from pathlib import Path

import numpy as np
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
from matplotlib.colors import LogNorm, TwoSlopeNorm
from scipy.stats import pearsonr, spearmanr

REPO = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO / "notes"))
from rev_phiid_fast import atoms_from_corr, ar1_corr, ATOMS

RES, RR, FIG = REPO / "results", REPO / "notes" / "review_results", REPO / "manuscript" / "figures"
FIG.mkdir(exist_ok=True)
IX = {n: i for i, n in enumerate(ATOMS)}
PRE, POST = np.arange(0, 4), np.arange(5, 14)
SEED = 20261120
rng = np.random.default_rng(SEED)
try:
    GIT = subprocess.check_output(["git", "rev-parse", "--short", "HEAD"], cwd=REPO, text=True).strip()
except Exception:
    GIT = "nogit"
plt.rcParams.update({"font.size": 9, "axes.spines.top": False, "axes.spines.right": False, "figure.dpi": 150, "savefig.dpi": 300})
C_MMI, C_CCS, C_DMT, C_PCB, C_PRED, C_RES = "#4C72B0", "#DD8452", "#C44E52", "#4C72B0", "#55A868", "#8172B3"
captions = ["# Figure captions (draft_v2)", "", f"Generated by `scripts/15_figures_v2.py` at git {GIT}, seed {SEED}. Every value is read from the saved results files named under each figure.", ""]


def did_per_subject(A):
    """A: (14, 2, 14 windows[, k]) → per-subject primary DiD (post windows 6–14 minus pre 1–4, DMT minus placebo)."""
    ch = A[:, :, POST].mean(2) - A[:, :, PRE].mean(2)
    return ch[:, 0] - ch[:, 1]


def boot_ci(v, n=10000):
    v = np.asarray(v, float)
    draws = v[rng.integers(0, v.size, (n, v.size))].mean(1)
    return np.percentile(draws, [2.5, 97.5])


def save(fig, stem):
    fig.savefig(FIG / f"{stem}.png", bbox_inches="tight")
    fig.savefig(FIG / f"{stem}.pdf", bbox_inches="tight")
    plt.close(fig)
    print("wrote", FIG / f"{stem}.png")


# ------------------------------------------------------------------ Figure 1: sixteen atoms, MMI vs CCS
mmi = np.load(RES / "atoms_win60_115regions-all_ts_gsr_window.npy")               # (14, 2, 14, 16)
ccs = np.load(RR / "partB" / "ccs_pub_atoms_win60_ts_gsr.npy")
order = ["rtr", "rtx", "rty", "xtr", "ytr", "xty", "ytx", "xtx", "yty", "rts", "str", "xts", "yts", "stx", "sty", "sts"]
groups = [("double\nredundancy", ["rtr"]), ("cross-prediction", ["rtx", "rty", "xtr", "ytr", "xty", "ytx"]), ("self-\nprediction", ["xtx", "yty"]),
          ("redundancy ↔\nsynergy", ["rts", "str"]), ("mirror atoms", ["xts", "yts", "stx", "sty"]), ("synergy", ["sts"])]
lvl_m, lvl_c = mmi[:, 0][:, PRE].mean((0, 1)), ccs[:, 0][:, PRE].mean((0, 1))
did_m = np.stack([did_per_subject(mmi[..., IX[a]]) for a in ATOMS], 1)         # (14 subjects, 16)
did_c = np.stack([did_per_subject(ccs[..., IX[a]]) for a in ATOMS], 1)
fig, axes = plt.subplots(2, 1, figsize=(8.6, 6.2), sharex=True, gridspec_kw=dict(hspace=0.12))
x = np.arange(16); wbar = 0.38
for ax, (vm, vc, ylab, title) in zip(axes, ((lvl_m, lvl_c, "atom value, DMT pre-injection (nats)", "a  level (windows 1–4, DMT run)"),
                                            (did_m.mean(0), did_c.mean(0), "primary DiD (nats)", "b  DMT − placebo, post − pre (windows 6–14 vs 1–4)"))):
    vals_m = [vm[IX[a]] for a in order]; vals_c = [vc[IX[a]] for a in order]
    ax.bar(x - wbar / 2, vals_m, wbar, color=C_MMI, label="MMI")
    ax.bar(x + wbar / 2, vals_c, wbar, color=C_CCS, label="CCS (published definition)")
    if ylab.startswith("primary"):
        for k, a in enumerate(order):
            for off, d, col in ((-wbar / 2, did_m[:, IX[a]], C_MMI), (wbar / 2, did_c[:, IX[a]], C_CCS)):
                lo, hi = boot_ci(d)
                ax.plot([x[k] + off] * 2, [lo, hi], color="black", lw=0.8)
    ax.axhline(0, color="black", lw=0.6)
    ax.set_ylabel(ylab); ax.set_title(title, loc="left", fontsize=9.5)
    for g0 in np.cumsum([len(g[1]) for g in groups])[:-1]:
        ax.axvline(g0 - 0.5, color="0.85", lw=0.8)
axes[0].legend(frameon=False, loc="upper left")
axes[1].set_xticks(x); axes[1].set_xticklabels(order)
pos = 0
for name, members in groups:
    axes[1].text(pos + (len(members) - 1) / 2, axes[1].get_ylim()[0] - 0.22 * np.diff(axes[1].get_ylim())[0], name, ha="center", va="top", fontsize=7.5, color="0.35")
    pos += len(members)
axes[0].annotate(f"sts − (xtx + yty) = {lvl_m[IX['sts']] - lvl_m[IX['xtx']] - lvl_m[IX['yty']]:+.3f} under MMI\n(the AR(1) family gives +rtr = {lvl_m[IX['rtr']]:+.3f})",
                 xy=(15, lvl_m[IX["sts"]]), xytext=(9.3, 0.95), fontsize=7.5, arrowprops=dict(arrowstyle="-", color="0.5", lw=0.6))
save(fig, "fig1_v2_atoms_mmi_ccs")
captions += ["## Figure 1", "",
             f"The sixteen Gaussian ΦID atoms of the whole-brain pair mean (6,555 pairs, 14 subjects, ts_gsr, windowed estimator W = 60) under the MMI redundancy function (blue) and under CCS with the published double-redundancy definition (orange). (a) DMT pre-injection level (windows 1–4). (b) Primary difference-in-differences, DMT minus placebo, post (windows 6–14) minus pre (windows 1–4); whiskers are subject-bootstrap 95 % CIs (10,000 draws). Atom codes: first letter the past-side type, last letter the future-side type (r redundant, x unique to region X, y unique to Y, s synergistic; e.g. rts = redundancy-to-synergy). Under MMI the synergy block sts + rts + str (+{lvl_m[IX['sts']] + lvl_m[IX['rts']] + lvl_m[IX['str']]:.3f} nats) is offset by the four negative mirror atoms ({lvl_m[IX['xts']] + lvl_m[IX['yts']] + lvl_m[IX['stx']] + lvl_m[IX['sty']]:+.3f}), sts sits {abs(lvl_m[IX['sts']] - lvl_m[IX['xtx']] - lvl_m[IX['yty']]):.3f} nats below xtx + yty (the AR(1) family predicts sts − (xtx + yty) = rtr = +{lvl_m[IX['rtr']]:.3f}), and under DMT the block falls while the mirrors rise. Under CCS the mirror atoms, rts and str are near zero, sts is {lvl_c[IX['sts']]:+.3f} nats, and xtx and yty keep their MMI values and DiDs. Source: `results/atoms_win60_115regions-all_ts_gsr_window.npy`, `notes/review_results/partB/ccs_pub_atoms_win60_ts_gsr.npy`.", ""]

# ------------------------------------------------------------------ Figure 2: scope map with real pairs
def grid(qlim):
    r1g = np.arange(0.0, 0.951, 0.005); qg = np.arange(-qlim, qlim + 1e-9, 0.005)
    R1, Q = np.meshgrid(r1g, qg, indexing="ij")
    A = atoms_from_corr(ar1_corr(R1.ravel(), R1.ravel(), Q.ravel()))
    sts = A[:, IX["sts"]].reshape(R1.shape); selfp = (A[:, IX["xtx"]] + A[:, IX["yty"]]).reshape(R1.shape)
    h = 1e-3
    dr = (atoms_from_corr(ar1_corr((R1 + h).ravel(), (R1 + h).ravel(), Q.ravel()))[:, IX["sts"]] - atoms_from_corr(ar1_corr((R1 - h).ravel(), (R1 - h).ravel(), Q.ravel()))[:, IX["sts"]]).reshape(R1.shape) / (2 * h)
    dq = (atoms_from_corr(ar1_corr(R1.ravel(), R1.ravel(), (Q + h).ravel()))[:, IX["sts"]] - atoms_from_corr(ar1_corr(R1.ravel(), R1.ravel(), (Q - h).ravel()))[:, IX["sts"]]).reshape(R1.shape) / (2 * h)
    return r1g, qg, R1, Q, sts, selfp, np.abs(dr) / np.maximum(np.abs(dq), 1e-12)


r1g, qg, R1, Q, sts, selfp, ratio = grid(0.6)
r1w, qw, R1w, Qw, stsw, selfw, ratiow = grid(0.95)
ov = np.load(RR / "partB" / "scope_map_overlay_points.npz")
fig, axes = plt.subplots(1, 3, figsize=(13.0, 4.1), constrained_layout=True)
ext = [qg[0], qg[-1], r1g[0], r1g[-1]]
im0 = axes[0].imshow(sts, origin="lower", extent=ext, aspect="auto", cmap="Blues")
fig.colorbar(im0, ax=axes[0], fraction=0.05, pad=0.02, label="sts (nats)")
cs0 = axes[0].contour(Q, R1, sts, levels=[0.25, 0.5, 1.0, 1.5, 2.0], colors="k", linewidths=0.5)
axes[0].clabel(cs0, fmt="%.2g", fontsize=6.5)
axes[0].set_title("a  sts = −ln(1 − r₁²) + ½ ln(1 − r₁²q²)", loc="left", fontsize=9)
im1 = axes[1].imshow(sts - selfp, origin="lower", extent=ext, aspect="auto", cmap="Reds")
fig.colorbar(im1, ax=axes[1], fraction=0.05, pad=0.02, label="sts − (xtx + yty) = rtr (nats)")
axes[1].set_title("b  the excess of sts over self-prediction (= rtr)", loc="left", fontsize=9)
maskw = R1w > 0.005
extw = [qw[0], qw[-1], r1w[0], r1w[-1]]
im2 = axes[2].imshow(np.where(maskw, ratiow, np.nan), origin="lower", extent=extw, aspect="auto", cmap="viridis", norm=LogNorm(vmin=3, vmax=300))
fig.colorbar(im2, ax=axes[2], fraction=0.05, pad=0.02, label="|∂sts/∂r₁| / |∂sts/∂q|")
cs2 = axes[2].contour(Qw, R1w, np.where(maskw, ratiow, np.nan), levels=[10, 30, 100], colors="white", linewidths=0.6)
axes[2].clabel(cs2, fmt="%g", fontsize=6.5)
sub = rng.choice(ov["dmt_w6_r1"].size, 1500, replace=False)
axes[2].scatter(ov["dmt_w6_q"][sub], ov["dmt_w6_r1"][sub], s=2.5, color="#FF6F00", alpha=0.5, lw=0, label="real pairs (subject 1, DMT window 6)")
axes[2].scatter([0.25], [0.85], marker="x", color="black", s=50, lw=1.4, zorder=5, label="operating point (0.85, 0.25)")
rmin = float(np.nanmin(np.where(maskw, ratiow, np.nan)))
r_op = ratio[np.argmin(np.abs(r1g - 0.85)), np.argmin(np.abs(qg - 0.25))]
imin = np.unravel_index(np.nanargmin(np.where(maskw, ratiow, np.nan)), ratiow.shape)
leg = axes[2].legend(frameon=False, loc="upper center", bbox_to_anchor=(0.5, -0.16), fontsize=7.5, ncol=2, markerscale=2.5)
axes[2].set_title("c  which input sts responds to (no ratio = 1 boundary exists)", loc="left", fontsize=9)
for ax in axes:
    ax.set_xlabel("q, lag-0 cross-correlation"); ax.set_ylabel("r₁, lag-1 autocorrelation")
save(fig, "fig2_v2_scope_map")
captions += ["## Figure 2", "",
             f"The scope map: Gaussian-MMI sts of a bivariate AR(1) pair as a function of the pair's lag-1 autocorrelation r₁ and lag-0 cross-correlation q (closed form of Methods; grid step 0.005). (a) sts. (b) sts − (xtx + yty), which on the family equals rtr and vanishes at q = 0. (c) The ratio of the two partial derivatives |∂sts/∂r₁| / |∂sts/∂q| on the wider grid |q| ≤ 0.95 (log colour scale; central differences, h = 0.001) with contours at 10, 30 and 100; the boundary at which the two inputs would contribute equally (ratio = 1) does not exist on the grid — the ratio's minimum for r₁ > 0 is {rmin:.1f}, at (r₁, q) = ({r1w[imin[0]]:.2f}, {qw[imin[1]]:+.2f}), and 6.55 on the grid |q| ≤ 0.6 of the text — so the family has no q-dominated region, and the placement of real pairs on it is informative only through the operating point and the ratio there, not through membership of a region. Orange points: 1,500 of the 6,555 region pairs of subject 1 (ts_gsr, DMT run, window 6; r₁ = mean of the two regions' within-window lag-1 autocorrelations, q = the pair's within-window lag-0 correlation; median r₁ {np.median(ov['dmt_w6_r1']):.3f}, median |q| {np.median(np.abs(ov['dmt_w6_q'])):.3f}); the cross marks the operating point (0.85, 0.25) used for the derivative values in the text, where the ratio is {r_op:.0f}. Source: `notes/rev_phiid_fast.py` (closed form), `notes/review_results/partB/scope_map_overlay_points.npz`.", ""]

# ------------------------------------------------------------------ Figure 3: per-subject scatters
def rows(f):
    return pickle.load(open(RR / f"inference_rows_{f}.pkl", "rb"))


def get(rs, label, st="primary"):
    return np.asarray([r for r in rs if r["label"] == label and r["set"] == st][0]["did_subjects"], float)


raw, diag, ccsp = rows("raw"), rows("diag"), rows("ccs_pub")
d_sts, d_ac = get(raw, "sts ts_gsr W60"), get(raw, "autocorr ts_gsr W60")
d_res, d_ccs = get(diag, "diag residual sts ts_gsr W60"), get(ccsp, "CCSpub sts ts_gsr W60")
fig, axes = plt.subplots(1, 2, figsize=(9.2, 4.0), gridspec_kw=dict(wspace=0.3))
for ax, (xv, yv, xl, yl, title) in zip(axes, ((d_ac, d_sts, "lag-1 autocorrelation DiD", "MMI-sts DiD (nats)", "a  the sts contrast against the autocorrelation contrast"),
                                             (d_res, d_ccs, "residual DiD of the diagnostic (nats)", "CCS-sts DiD, published definition (nats)", "b  the two remainders"))):
    r, p = pearsonr(xv, yv); rho = spearmanr(xv, yv)[0]
    b = np.polyfit(xv, yv, 1); xx = np.linspace(xv.min(), xv.max(), 10)
    ax.plot(xx, np.polyval(b, xx), color="0.6", lw=0.8)
    ax.scatter(xv, yv, s=28, color="0.15", zorder=3)
    for k in range(14):
        ax.annotate(str(k + 1), (xv[k], yv[k]), xytext=(3, 3), textcoords="offset points", fontsize=6.5, color="0.4")
    ax.axhline(0, color="0.8", lw=0.6); ax.axvline(0, color="0.8", lw=0.6)
    ax.set_xlabel(xl); ax.set_ylabel(yl); ax.set_title(title, loc="left", fontsize=9)
    ax.text(0.03, 0.95, f"r = {r:+.3f} (p = {p:.3g}), ρ = {rho:+.2f}, N = 14", transform=ax.transAxes, fontsize=8, va="top")
save(fig, "fig3_v2_per_subject")
r_a, r_b = pearsonr(d_ac, d_sts)[0], pearsonr(d_res, d_ccs)[0]
captions += ["## Figure 3", "",
             f"Per-subject difference-in-differences (post windows 6–14 minus pre windows 1–4, DMT minus placebo; ts_gsr, W = 60; one dot per subject, labelled by index). (a) Whole-brain MMI-sts DiD against the mean regional lag-1 autocorrelation DiD (Pearson r = {r_a:+.3f}). (b) CCS-sts DiD (published double-redundancy definition) against the residual DiD of the diagnostic (observed sts minus the AR(1) prediction from each pair's measured a_x, a_y, q; Pearson r = {r_b:+.3f}); both quantities are computed from the same windows, so a shared component can be signal or estimation noise — the split-half test of Results 4 separates them. Grey line: least-squares fit. Source: `notes/review_results/inference_rows_raw.pkl`, `inference_rows_diag.pkl`, `inference_rows_ccs_pub.pkl` (field `did_subjects`, primary set).", ""]

# ------------------------------------------------------------------ Figure 4: residual diagnostic by window
z = np.load(RR / "partB" / "diag_series_ts_gsr_W60.npz")
obs, pred, res = z["obs"], z["pred"], z["res"]                                   # (14, 2, 14)
t = (np.arange(14) + 0.5) * 2.0                                                  # window centre, minutes
fig, axes = plt.subplots(2, 1, figsize=(7.8, 6.0), sharex=True, gridspec_kw=dict(hspace=0.15, height_ratios=[1.35, 1]))
for ax in axes:
    ax.axvspan(0, 8, color="0.92", zorder=0); ax.axvspan(8, 10, facecolor="none", hatch="///", edgecolor="0.6", lw=0, zorder=0)
    ax.axvline(8, color="k", ls="--", lw=0.8)
for c, cname, col in ((0, "DMT", C_DMT), (1, "placebo", C_PCB)):
    for arr, ls, lab in ((obs, "-", "observed"), (pred, "--", "AR(1) prediction")):
        m = arr[:, c].mean(0); se = arr[:, c].std(0, ddof=1) / np.sqrt(14)
        axes[0].plot(t, m, ls=ls, color=col, lw=1.4, label=f"{cname}, {lab}")
        if ls == "-":
            axes[0].fill_between(t, m - se, m + se, color=col, alpha=0.15, lw=0)
    m = res[:, c].mean(0); se = res[:, c].std(0, ddof=1) / np.sqrt(14)
    axes[1].plot(t, m, color=col, lw=1.4, label=f"{cname}, residual = observed − predicted"); axes[1].fill_between(t, m - se, m + se, color=col, alpha=0.15, lw=0)
axes[0].set_ylabel("whole-brain mean sts (nats)"); axes[1].set_ylabel("residual (nats)"); axes[1].set_xlabel("time in scan (min)")
axes[0].set_title("a  observed sts and the prediction from each pair's measured (a_x, a_y, q)", loc="left", fontsize=9)
axes[1].set_title("b  the residual", loc="left", fontsize=9)
axes[0].legend(frameon=False, fontsize=7.5, ncol=2, loc="lower right"); axes[1].legend(frameon=False, fontsize=7.5, loc="upper right")
axes[1].axhline(0, color="k", lw=0.5)
save(fig, "fig4_v2_residual_diagnostic")
did_o, did_p, did_r = did_per_subject(obs).mean(), did_per_subject(pred).mean(), did_per_subject(res).mean()
captions += ["## Figure 4", "",
             f"The residual diagnostic by window (ts_gsr, W = 60, N = 14; lines are group means, shading ± 1 SEM across subjects; grey band = pre-injection windows 1–4, hatched = window 5, excluded from the primary post set; dashed line = injection at 8 min). (a) Observed whole-brain sts (solid) and the sts predicted from each pair's measured lag-1 autocorrelations a_x, a_y and lag-0 correlation q alone (dashed), DMT (red) and placebo (blue). (b) The residual, observed minus predicted, per run. The prediction over-shoots the level by {abs(res.mean()):.3f} nats and the primary DiD by {abs(did_p) - abs(did_o):.4f} nats (observed {did_o:+.4f}, predicted {did_p:+.4f}, residual DiD {did_r:+.4f}); the residual is least negative in the drug-present windows of the DMT run. Source: `notes/review_results/partB/diag_series_ts_gsr_W60.npz`.", ""]

(FIG / "captions_v2.md").write_text("\n".join(captions) + "\n")
print("wrote", FIG / "captions_v2.md")
