"""Compares the figures and captions that scripts/15_figures_v2.py has just written with the committed ones (HEAD).

Planning session, 30 Sep 2026 (record, "Fig 5's caption, B3's table header and `run_all.sh`'s timing comment"). Run from
the repository root after `.venv/bin/python scripts/15_figures_v2.py`, before anything is committed:
    .venv/bin/python notes/review_2026-09-30/checks/figures_check.py
It prints, for `manuscript/figures/captions_v2.md`, every line that differs from HEAD's; for each PNG of the six
figures, whether its bytes are identical and, if not, how many pixels differ and by how much at most; for each PDF,
whether its bytes are identical once its creation date is masked, with the byte offsets that follow from the date's
length. The conditions of the record's entry: the captions differ only in their header line and in Fig 5's caption, the
PNG files are identical and the PDF files differ only in their dates. It ends with "conditions met" (exit status 0) or
says that they are not met (exit status 1); it changes no file.
"""
import io, re, subprocess, sys
from pathlib import Path
import numpy as np
from PIL import Image

FIG = Path("manuscript/figures")
NAMES = ("fig1_v2_scope_map", "fig2_v2_atoms_observed_substituted", "fig3_v2_per_subject", "fig4_v2_regional",
         "fig5_v2_residual_diagnostic", "fig6_v2_lag_dependence")   # the six figures the script writes


def committed(path):
    r = subprocess.run(["git", "show", f"HEAD:{path}"], capture_output=True)
    if r.returncode:
        sys.exit(f"git show HEAD:{path} failed: {r.stderr.decode(errors='replace').strip()}")
    return r.stdout


ok = True
old = committed(f"{FIG}/captions_v2.md").decode("utf-8").split("\n")
new = (FIG / "captions_v2.md").read_text(encoding="utf-8").split("\n")
if len(old) != len(new):
    print(f"captions_v2.md: {len(old)} lines at HEAD, {len(new)} now")
    ok = False
diff = [i for i in range(min(len(old), len(new))) if old[i] != new[i]]
for i in diff:
    what = ("the header" if old[i].startswith("Generated by `scripts/15_figures_v2.py` at git ")
            else "Fig 5's caption" if old[i].startswith("**Fig 5. ") and new[i].startswith("**Fig 5. ") else "OTHER")
    print(f"captions_v2.md line {i + 1} ({what}):\n  HEAD: {old[i]}\n  now:  {new[i]}")
    ok &= what != "OTHER"
if not diff:
    print("captions_v2.md: identical to HEAD")

for png in (FIG / f"{n}.png" for n in NAMES):
    a, b = committed(str(png)), png.read_bytes()
    if a == b:
        print(f"{png.name}: identical")
        continue
    x = np.asarray(Image.open(io.BytesIO(a)).convert("RGBA"), dtype=int)
    y = np.asarray(Image.open(io.BytesIO(b)).convert("RGBA"), dtype=int)
    if x.shape != y.shape:
        print(f"{png.name}: DIFFERS, size {x.shape} at HEAD, {y.shape} now")
    else:
        d = np.abs(x - y)
        n = int(np.any(d > 0, axis=2).sum())
        print(f"{png.name}: DIFFERS in {n} pixels, the largest channel difference {int(d.max())} of 255")
    ok = False

DATES = re.compile(rb"/(CreationDate|ModDate) \(D:[^)]*\)")


def masked(p):
    """The PDF with its dates masked, and its cross-reference table and offset, which move with the dates' length."""
    p = DATES.sub(b"/DATE", p)
    p = re.sub(rb"\nxref\n.*?\ntrailer", b"\nxref trailer", p, flags=re.S)
    return re.sub(rb"startxref\n\d+", b"startxref", p)


for pdf in (FIG / f"{n}.pdf" for n in NAMES):
    a, b = committed(str(pdf)), pdf.read_bytes()
    if a == b:
        print(f"{pdf.name}: identical")
    elif masked(a) == masked(b):
        print(f"{pdf.name}: differs only in its creation date (and the byte offsets that follow from its length)")
    else:
        print(f"{pdf.name}: DIFFERS beyond its dates")
        ok = False

print("conditions met" if ok else "conditions NOT met: send this output to the planning session")
sys.exit(0 if ok else 1)
